version: "2"

linters:
  default: standard
  enable:
    - revive
    - misspell
    - gosec
    - gocyclo
    - bodyclose
  settings:
    gocyclo:
      min-complexity: 15
run:
  tests: true
  timeout: 5m
